fix(CI/CD): debug test

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -59,7 +59,9 @@ jobs:
           path: backend/vendor
           key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}-v2
       - name: Install back dependencies
-        run: cd backend && composer install --no-progress --no-suggest --prefer-dist
+        run: |
+          cd backend
+          composer install --no-progress --no-suggest --prefer-dist --verbose
       - name: Lint back
         working-directory: backend
         run: vendor/bin/phpcs --standard=config/phpcs.xml app
@@ -213,11 +215,12 @@ jobs:
       - name: Run backend SQL tests
         run: |
           cd backend
+          composer install --no-progress --no-suggest --prefer-dist
           if [ -f "vendor/bin/phpunit" ]; then
             vendor/bin/phpunit --exclude-group mongodb
           else
-            echo "PHPUnit not found. Skipping test."
-            exit 0
+            echo "⚠️ PHPUnit not found. Please ensure it is installed as part of the dependencies."
+            exit 1
           fi
       - name: Run MongoDB NoSQL tests
         run: |
